roots = [
  '^Toml\.decode$',
  '^Toml\.encode$',
  '^Toml\.Pretty\.prettyTomlOrdered$',
  '^Toml\.ToValue\.\.=$',
  '^Toml\.ToValue\.table$',
  '^Toml\.ToValue\.Generic\.genericToTable$',
  '^Toml\.FromValue\.Generic\.genericParseTable$',
  '^Toml\.FromValue\.ParseTable\.warnTable$',
  '^Toml\.FromValue\.parseTableFromValue$',
]
type-class-roots = true
